// ═══════════════════════════════════════════════════════════
// Japão Express — Catálogo de Produtos
// Produtos adicionados via admin panel ou bot do Telegram.
// Estrutura de cada produto:
//   id, name, category, cat, subcategory,
//   priceBRL, priceJPY, weight,
//   description, details, origin,
//   image, image2, image3, images[],
//   units, featured, cost, markup,
//   badge, badgeBg, stock, rating, reviews,
//   cardBg, rotate, deco ('tape'|'pin')
// ═══════════════════════════════════════════════════════════

// ── Helpers ───────────────────────────────────────────────
function getProductById(id) {
  return PRODUCTS.find(p => p.id === id) || null;
}

const PRODUCTS = [
  {
    "id": "locao-clareadora-melano-cc",
    "name": "Loção Clareadora Medicated Melano CC Whitening Lotion 170ml",
    "category": "Cosméticos",
    "cat": "cosmeticos",
    "subcategory": "Loção",
    "brand": "Melano CC",
    "priceBRL": 33.22,
    "priceJPY": 850,
    "weight": 240,
    "description": "Loção facial japonesa com vitamina C para pele uniforme",
    "details": "<p>A Loção Clareadora Melano CC da Rohto é um dos cuidados faciais mais populares do Japão, desenvolvida com foco em uniformizar o tom da pele e combater manchas. Sua fórmula leve e refrescante entrega hidratação enquanto atua diretamente na aparência de marcas e tonalidade irregular.</p>\\n\\n<p><strong><i class=\"fa-solid fa-wand-magic-sparkles\"></i> Benefícios principais:</strong></p>\\n<ul>\\n<li>Ajuda a reduzir manchas escuras e marcas de acne</li>\\n<li>Uniformiza o tom da pele com uso contínuo</li>\\n<li>Contém vitamina C ativa para ação antioxidante</li>\\n<li>Textura leve, ideal para uso diário sem pesar</li>\\n<li>Hidrata e melhora a aparência geral da pele</li>\\n<li>Auxilia na prevenção de novas manchas</li>\\n</ul>\\n\\n<p><strong><i class=\"fa-solid fa-flask-vial\"></i> Ingredientes ou Composição:</strong></p>\\n<ul>\\n<li>Vitamina C (ácido ascórbico): ajuda no clareamento e ação antioxidante</li>\\n<li>Dipotassium Glycyrrhizate: auxilia na redução de inflamações</li>\\n<li>Extratos hidratantes: ajudam a manter a pele macia</li>\\n</ul>\\n\\n<p><strong><i class=\"fa-solid fa-hand-sparkles\"></i> Modo de uso:</strong></p>\\n<p>Após a limpeza do rosto, aplique uma quantidade adequada da loção nas mãos ou algodão e espalhe suavemente sobre a pele. Use diariamente, de manhã e à noite, antes do hidratante.</p>\\n\\n<p><strong><i class=\"fa-solid fa-shield-check\"></i> Por que escolher este produto?</strong></p>\\n<p>A linha Melano CC é extremamente popular no Japão e reconhecida por sua eficácia no cuidado com manchas e uniformização da pele. Produzida pela Rohto Pharmaceutical, uma marca tradicional com décadas de experiência, essa loção combina tecnologia japonesa com ingredientes ativos comprovados.</p>\\n\\n<p><strong><i class=\"fa-solid fa-triangle-exclamation\"></i> Aviso / Atenção:</strong></p>\\n<p>Evite contato com os olhos. Em caso de irritação, suspenda o uso. Não utilizar em pele lesionada. Recomenda-se o uso de protetor solar durante o dia.",
    "origin": "Japão",
    "image": "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mec/mec16966/l/2.jpg",
    "image2": "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mec/mec16966/l/3.jpg",
    "image3": "https://epocacosmeticos.vteximg.com.br/arquivos/ids/1361363-800-800/locao-hidratante-melano-cc-lotion%20-4-.jpg?v=639029723397030000",
    "images": [
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mec/mec16966/l/2.jpg",
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mec/mec16966/l/3.jpg",
      "https://epocacosmeticos.vteximg.com.br/arquivos/ids/1361363-800-800/locao-hidratante-melano-cc-lotion%20-4-.jpg?v=639029723397030000"
    ],
    "units": 1,
    "featured": false,
    "cost": 26.58,
    "markup": 25,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#d6eaf8]",
    "rotate": "rotate(1deg)",
    "deco": "tape",
    "createdAt": 1776569392385
  },
  {
    "id": "locao-clareadora-melano-cc",
    "name": "Loção Clareadora Medicated Melano CC Whitening Lotion 170ml",
    "category": "Cosméticos",
    "cat": "cosmeticos",
    "subcategory": "Loção",
    "brand": "Melano CC",
    "priceBRL": 31.27,
    "priceJPY": 800,
    "weight": 167,
    "description": "Loção facial japonesa com vitamina C para pele uniforme",
    "details": "<p>A Loção Clareadora Melano CC da Rohto é um dos cuidados faciais mais populares do Japão, desenvolvida com foco em uniformizar o tom da pele e combater manchas. Sua fórmula leve e refrescante entrega hidratação enquanto atua diretamente na aparência de marcas e tonalidade irregular.</p>\\n\\n<p><strong><i class=\"fa-solid fa-wand-magic-sparkles\"></i> Benefícios principais:</strong></p>\\n<ul>\\n<li>Ajuda a reduzir manchas escuras e marcas de acne</li>\\n<li>Uniformiza o tom da pele com uso contínuo</li>\\n<li>Contém vitamina C ativa para ação antioxidante</li>\\n<li>Textura leve, ideal para uso diário sem pesar</li>\\n<li>Hidrata e melhora a aparência geral da pele</li>\\n<li>Auxilia na prevenção de novas manchas</li>\\n</ul>\\n\\n<p><strong><i class=\"fa-solid fa-flask-vial\"></i> Ingredientes ou Composição:</strong></p>\\n<ul>\\n<li>Vitamina C (ácido ascórbico): ajuda no clareamento e ação antioxidante</li>\\n<li>Dipotassium Glycyrrhizate: auxilia na redução de inflamações</li>\\n<li>Extratos hidratantes: ajudam a manter a pele macia</li>\\n</ul>\\n\\n<p><strong><i class=\"fa-solid fa-hand-sparkles\"></i> Modo de uso:</strong></p>\\n<p>Após a limpeza do rosto, aplique uma quantidade adequada da loção nas mãos ou algodão e espalhe suavemente sobre a pele. Use diariamente, de manhã e à noite, antes do hidratante.</p>\\n\\n<p><strong><i class=\"fa-solid fa-shield-check\"></i> Por que escolher este produto?</strong></p>\\n<p>A linha Melano CC é extremamente popular no Japão e reconhecida por sua eficácia no cuidado com manchas e uniformização da pele. Produzida pela Rohto Pharmaceutical, uma marca tradicional com décadas de experiência, essa loção combina tecnologia japonesa com ingredientes ativos comprovados.</p>\\n\\n<p><strong><i class=\"fa-solid fa-triangle-exclamation\"></i> Aviso / Atenção:</strong></p>\\n<p>Evite contato com os olhos. Em caso de irritação, suspenda o uso. Não utilizar em pele lesionada. Recomenda-se o uso de protetor solar durante o dia.",
    "origin": "Japão",
    "image": "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mec/mec16966/l/2.jpg",
    "image2": "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mec/mec16966/l/3.jpg",
    "image3": "https://epocacosmeticos.vteximg.com.br/arquivos/ids/1361363-800-800/locao-hidratante-melano-cc-lotion%20-4-.jpg?v=639029723397030000",
    "images": [
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mec/mec16966/l/2.jpg",
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mec/mec16966/l/3.jpg",
      "https://epocacosmeticos.vteximg.com.br/arquivos/ids/1361363-800-800/locao-hidratante-melano-cc-lotion%20-4-.jpg?v=639029723397030000"
    ],
    "units": 1,
    "featured": false,
    "cost": 25.02,
    "markup": 25,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#d6eaf8]",
    "rotate": "rotate(-1deg)",
    "deco": "tape",
    "createdAt": 1776568524510
  },
  {
    "id": "senka-perfect-whip-espuma-de-limpeza-fac",
    "name": "Senka Perfect Whip Espuma de Limpeza Facial 120g",
    "category": "Cosméticos",
    "cat": "cosmeticos",
    "subcategory": "Limpeza Facial",
    "brand": "Shiseido",
    "priceBRL": 39.9,
    "priceJPY": 998,
    "weight": 120,
    "description": "Cleanser nº1 do Japão da Shiseido com espuma ultra densa.",
    "details": "<p>Um dos cleansers mais vendidos do Japão, desenvolvido pela renomada Shiseido, que conquistou milhões de pessoas pela sua espuma incrivelmente rica e eficiente.</p><p>O Senka Perfect Whip é um sabonete facial que cria uma espuma densa e cremosa capaz de limpar profundamente os poros sem ressecar a pele, proporcionando uma sensação imediata de frescor e maciez.</p><p><strong>✨ Benefícios principais:</strong></p><ul><li>Limpeza profunda sem agredir a pele</li><li>Remove oleosidade e impurezas com facilidade</li><li>Espuma ultra densa que reduz o atrito no rosto</li><li>Deixa a pele macia, hidratada e revitalizada</li></ul><p><strong>💧 Ingredientes-chave:</strong></p><ul><li>Ácido hialurônico → mantém a hidratação natural da pele</li><li>Silk Essence → proporciona toque suave e sedoso</li></ul><p><strong>🇯🇵 Por que escolher este produto?</strong></p><p>A linha Senka é desenvolvida pela Shiseido, uma das maiores marcas de cosméticos do Japão, reconhecida mundialmente por sua tecnologia avançada e qualidade superior. Isso garante um cuidado eficaz aliado a uma experiência sensorial única.</p><p>Sua espuma rica transforma a limpeza diária em um verdadeiro ritual de skincare japonês.</p><p><strong>🧴 Modo de uso:</strong></p><p>Aplique uma pequena quantidade nas mãos, adicione água e esfregue até formar uma espuma densa. Massageie suavemente o rosto e enxágue completamente.</p><p><strong>🔥 Prova social:</strong></p><ul><li>Bestseller absoluto no Japão</li><li>Altamente avaliado por milhares de usuários</li><li>Queridinho entre amantes de skincare asiático</li></ul><p>Se você quer uma pele limpa, macia e com qualidade japonesa de verdade, esse é o produto ideal para sua rotina.</p>",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775953539772_img_4649.jpeg",
    "image2": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775953548988_img_4651.jpeg",
    "image3": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775953559422_img_4650.jpeg",
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775953539772_img_4649.jpeg",
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775953548988_img_4651.jpeg",
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775953559422_img_4650.jpeg"
    ],
    "units": 1,
    "featured": true,
    "cost": 31.69,
    "markup": 23,
    "badge": null,
    "badgeBg": "#e74c3c",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#d6eaf8]",
    "rotate": "rotate(-1deg)",
    "deco": "tape",
    "createdAt": 1775953886973
  },
  {
    "id": "fino-premium-touch-mascara-capilar-230g",
    "name": "Fino Premium Touch Máscara Capilar 230g",
    "category": "Cabelos",
    "cat": "cabelos",
    "subcategory": "Máscara Capilar",
    "brand": null,
    "priceBRL": 57.14,
    "priceJPY": 880,
    "weight": 230,
    "description": "Tratamento japonês que repara, hidrata e deixa o cabelo sedoso instantaneamente",
    "details": "Ideal para cabelos ressecados, com química, descoloridos ou expostos ao calor constante, essa máscara entrega um efeito imediato de cabelo mais alinhado, macio e com brilho intenso — como se tivesse saído do salão.",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775478723920_13003_1.jpg",
    "image2": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775478130076_shiseidofinopreiumtouchhairmask230ml__1_.webp",
    "image3": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775478175734_fino.webp",
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775478723920_13003_1.jpg",
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775478130076_shiseidofinopreiumtouchhairmask230ml__1_.webp",
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775478175734_fino.webp"
    ],
    "units": 1,
    "featured": true,
    "cost": 28.57,
    "markup": 100,
    "badge": "Queridinho",
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#fcf3cf]",
    "rotate": "rotate(-2deg)",
    "deco": "tape"
  },
  {
    "id": "moroccan-beauty-deep-moist-shampoo-trata",
    "name": "Moroccan Beauty Deep Moist Shampoo + Tratamento",
    "category": "Cabelos",
    "cat": "cabelos",
    "subcategory": "Shampoo",
    "brand": null,
    "priceBRL": 207.8,
    "priceJPY": 3200,
    "weight": 900,
    "description": "Kit hidratante com óleo de argan para cabelos macios e brilhantes.",
    "details": "O Moroccan Beauty Deep Moist Shampoo + Tratamento é um kit premium japonês desenvolvido para hidratação profunda e reparação capilar. Enriquecido com óleo de argan, conhecido como 'ouro líquido', proporciona nutrição intensa, brilho e maciez desde a primeira aplicação.",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775571818122_content_2_picture.webp",
    "image2": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775571858065_moroccan.jpg",
    "image3": null,
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775571818122_content_2_picture.webp",
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775571858065_moroccan.jpg"
    ],
    "units": 1,
    "featured": true,
    "cost": 103.9,
    "markup": 100,
    "badge": "Favorito JP",
    "badgeBg": "#9b59b6",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#fadbd8]",
    "rotate": "rotate(-1deg)",
    "deco": "tape"
  },
  {
    "id": "kit-ma-me-repair-danos-sem-silicone-para",
    "name": "Kit ma&me Repair Danos Sem Silicone (Para Pais e Filhos)",
    "category": "Cabelos",
    "cat": "cabelos",
    "subcategory": "Shampoo",
    "brand": null,
    "priceBRL": 83.42,
    "priceJPY": 1300,
    "weight": 500,
    "description": "Shampoo e condicionador japonês suave, sem silicone, ideal para toda a família",
    "details": "O kit ma&me Aminoácido Repair é um tratamento capilar japonês desenvolvido para reparar cabelos danificados de forma suave e eficaz. Sua fórmula sem silicone é segura para uso diário e indicada para toda a família, inclusive crianças.",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775818047307_skuimg-d_79851_xl.jpg",
    "image2": null,
    "image3": null,
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775818047307_skuimg-d_79851_xl.jpg"
    ],
    "units": 1,
    "featured": false,
    "cost": 41.71,
    "markup": 100,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#fadbd8]",
    "rotate": "rotate(-1deg)",
    "deco": "tape"
  },
  {
    "id": "ma-me-latte-kit-premium-w-milk-protein",
    "name": "Ma & Me Latte kit Premium W Milk Protein",
    "category": "Cabelos",
    "cat": "cabelos",
    "subcategory": "Shampoo",
    "priceBRL": 83.42,
    "priceJPY": 1300,
    "weight": 500,
    "description": "Kit aponês nutritivo com proteína do leite para cabelos macios.",
    "details": "O Ma & Me Latte Premium W Milk Protein é um tratamento capilar japonês desenvolvido para nutrir profundamente cabelos danificados, especialmente de adultos e crianças.",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775818367083_31dbfgmu-yl._ac_uf894_1000_ql80_.jpg",
    "image2": null,
    "image3": null,
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775818367083_31dbfgmu-yl._ac_uf894_1000_ql80_.jpg"
    ],
    "units": 1,
    "featured": false,
    "cost": 41.71,
    "markup": 100,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#fadbd8]",
    "rotate": "rotate(1deg)",
    "deco": "tape"
  },
  {
    "id": "softymo-super-cleansing-wash-colageno",
    "name": "Softymo Super Cleansing Wash Colágeno",
    "category": "Cosméticos",
    "cat": "cosmeticos",
    "subcategory": "Limpeza facial",
    "priceBRL": 44.92,
    "priceJPY": 700,
    "weight": 190,
    "description": "Limpeza facial profunda com colágeno para pele hidratada e macia.",
    "details": "O Softymo Super Cleansing Wash com Colágeno é um sabonete facial japonês de alta qualidade desenvolvido para remover impurezas, oleosidade e resíduos de maquiagem enquanto hidrata profundamente a pele.",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775816890370_9787226016_001.avif",
    "image2": null,
    "image3": null,
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775816890370_9787226016_001.avif"
    ],
    "units": 1,
    "featured": false,
    "cost": 22.46,
    "markup": 100,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#d5f5e3]",
    "rotate": "rotate(-1deg)",
    "deco": "tape"
  },
  {
    "id": "moroccan-beauty-deep-moist-hidratante-re",
    "name": "Moroccan Beauty Deep Moist Hidratante Refil Óleo de Argan 400ml",
    "category": "Cabelos",
    "cat": "cabelos",
    "subcategory": "Tratamento",
    "priceBRL": 78.58,
    "priceJPY": 1210,
    "weight": 420,
    "description": "Shampoo hidratante com óleo de argan para cabelos macios e brilhantes.",
    "details": "O Moroccan Beauty Deep Moist Hidratante Refil é um hidratante japonês enriquecido com óleo de argan marroquino, conhecido por suas propriedades nutritivas e restauradoras.",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775573921822_61fw2kd0rvl._ac_sx679_.jpg",
    "image2": null,
    "image3": null,
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775573921822_61fw2kd0rvl._ac_sx679_.jpg"
    ],
    "units": 1,
    "featured": false,
    "cost": 39.29,
    "markup": 100,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#fadbd8]",
    "rotate": "rotate(-2deg)",
    "deco": "tape"
  },
  {
    "id": "moroccan-beauty-hydro-repair-hidratante-",
    "name": "Moroccan Beauty Hydro Repair Hidratante Refil 400ml",
    "category": "Cabelos",
    "cat": "cabelos",
    "subcategory": "Tratamento",
    "priceBRL": 78.58,
    "priceJPY": 1210,
    "weight": 420,
    "description": "Tratamento japonês com óleo de argan para reparar e hidratar profundamente os fios.",
    "details": "O Moroccan beauty Repair Treatment é um tratamento capilar japonês intensivo desenvolvido para reparar profundamente cabelos danificados, proporcionando hidratação, maciez e brilho duradouro.",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775573039618_344861_1_800.jpg",
    "image2": null,
    "image3": null,
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775573039618_344861_1_800.jpg"
    ],
    "units": 1,
    "featured": false,
    "cost": 39.29,
    "markup": 100,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#fcf3cf]",
    "rotate": "rotate(-2deg)",
    "deco": "tape"
  },
  {
    "id": "moroccan-beauty-deep-moist-shampoo-refil",
    "name": "Moroccan Beauty Deep Moist Shampoo Refil Óleo de Argan 400ml",
    "category": "Cabelos",
    "cat": "cabelos",
    "subcategory": "Shampoo",
    "priceBRL": 78.58,
    "priceJPY": 1210,
    "weight": 420,
    "description": "Shampoo com óleo de argan para cabelos macios e brilhantes.",
    "details": "O Moroccan Beauty Deep Moist Shampoo é um shampoo japonês enriquecido com óleo de argan marroquino, conhecido por suas propriedades nutritivas e restauradoras.",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775569991571_61zqhu_r-pl._ac_uf350_350_ql80_.jpg",
    "image2": null,
    "image3": null,
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775569991571_61zqhu_r-pl._ac_uf350_350_ql80_.jpg"
    ],
    "units": 1,
    "featured": false,
    "cost": 39.29,
    "markup": 100,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#fadbd8]",
    "rotate": "rotate(1deg)",
    "deco": "tape"
  },
  {
    "id": "moroccan-beauty-golden-moist-ex-shampoo-",
    "name": "Moroccan Beauty Golden Moist EX Shampoo + Tratamento",
    "category": "Cabelos",
    "cat": "cabelos",
    "subcategory": "Shampoo",
    "priceBRL": 228.58,
    "priceJPY": 3520,
    "weight": 900,
    "description": "Hidratação intensa premium com óleo de argan para brilho e maciez extrema.",
    "details": "O Moroccan Beauty Golden Moist EX Shampoo + Tratamento é um kit premium japonês desenvolvido para proporcionar hidratação intensa e nutrição profunda aos cabelos. Sua fórmula avançada com óleo de argan e ingredientes nutritivos penetra profundamente nos fios, restaurando danos, reduzindo o frizz e deixando o cabelo extremamente macio e brilhante.",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775572509333_gold.jpg",
    "image2": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775572514701_52353-83-6f2aef34a6b1f1c30e0c237576d75b6b-2000x1020.webp",
    "image3": null,
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775572509333_gold.jpg",
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775572514701_52353-83-6f2aef34a6b1f1c30e0c237576d75b6b-2000x1020.webp"
    ],
    "units": 1,
    "featured": false,
    "cost": 114.29,
    "markup": 100,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#d6eaf8]",
    "rotate": "rotate(2deg)",
    "deco": "tape"
  },
  {
    "id": "moroccan-beauty-hydro-repair-shampoo-tra",
    "name": "Moroccan Beauty Hydro Repair Shampoo + Tratamento",
    "category": "Cabelos",
    "cat": "cabelos",
    "subcategory": "Shampoo",
    "priceBRL": 207.8,
    "priceJPY": 3200,
    "weight": 900,
    "description": "Reparação intensa com hidratação profunda para cabelos danificados.",
    "details": "O Moroccan Beauty Hydro Repair Shampoo + Tratamento é um kit japonês avançado desenvolvido para reparar profundamente cabelos danificados, ressecados ou quimicamente tratados. Sua fórmula combina hidratação intensa com tecnologia de reconstrução capilar, restaurando a saúde e o brilho dos fios.",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775571903848_content_2_picture__1_.webp",
    "image2": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775571912133______.jpg",
    "image3": null,
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775571903848_content_2_picture__1_.webp",
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775571912133______.jpg"
    ],
    "units": 1,
    "featured": false,
    "cost": 103.9,
    "markup": 100,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#fcf3cf]",
    "rotate": "rotate(1deg)",
    "deco": "tape"
  },
  {
    "id": "ino-premium-touch-oleo-capilar",
    "name": "Fino Premium Touch Óleo Capilar Concentrado 70ml",
    "category": "Cabelos",
    "cat": "cabelos",
    "subcategory": "Óleo Capilar",
    "priceBRL": 63.64,
    "priceJPY": 980,
    "weight": 120,
    "description": "Óleo japonês que repara danos e deixa o cabelo sedoso e brilhante.",
    "details": "Fino Premium Touch Óleo Capilar é um tratamento intensivo sem enxágue desenvolvido no Japão para restaurar cabelos danificados.\n\nBenefícios principais:\n• Repara profundamente fios danificados\n• Proporciona brilho intenso e toque sedoso\n• Reduz frizz e pontas duplas\n• Textura leve, não oleosa\n• Perfume floral elegante japonês",
    "origin": "Japão",
    "image": "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775479346447_244833_1_800.jpg",
    "image2": null,
    "image3": null,
    "images": [
      "https://cdn.jsdelivr.net/gh/igorngf1re/japaoexpress@main/images/produtos/1775479346447_244833_1_800.jpg"
    ],
    "units": 1,
    "featured": false,
    "cost": 31.82,
    "markup": 100,
    "badge": null,
    "badgeBg": "#f5a623",
    "stock": 10,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#d6eaf8]",
    "rotate": "rotate(2deg)",
    "deco": "tape"
  },
  {
    "id": "locao-facial-clareadora-hada-labo-shiroj",
    "name": "Loção Facial Clareadora Hada Labo Shirojyun Premium 170ml - Rohto",
    "category": "Cosméticos",
    "cat": "cosmeticos",
    "subcategory": "Cuidados com a Pele",
    "priceBRL": 64.28,
    "priceJPY": 990,
    "weight": 170,
    "description": "Loção japonesa premium que clareia e hidrata profundamente a pele.",
    "details": "A Loção Facial Clareadora Hada Labo Shirojyun Premium da Rohto é um cosmético japonês de alta qualidade desenvolvido para hidratar profundamente e combater manchas e tonalidade irregular da pele.\nBenefícios principais:\n• Clareia e uniformiza o tom da pele\n• Hidratação intensa com ácido hialurônico\n• Ajuda a prevenir manchas e sardas\n• Ação calmante e anti-inflamatória",
    "origin": "Japão",
    "image": "https://donki-ec-static-1306051524.cos.ap-hongkong.myqcloud.com/images/4987241168491-1.jpg",
    "image2": "https://donki-ec-static-1306051524.cos.ap-hongkong.myqcloud.com/images/4987241168491-2.jpg",
    "image3": "https://donki-ec-static-1306051524.cos.ap-hongkong.myqcloud.com/images/4987241168491-3.jpg",
    "images": [
      "https://donki-ec-static-1306051524.cos.ap-hongkong.myqcloud.com/images/4987241168491-1.jpg",
      "https://donki-ec-static-1306051524.cos.ap-hongkong.myqcloud.com/images/4987241168491-2.jpg",
      "https://donki-ec-static-1306051524.cos.ap-hongkong.myqcloud.com/images/4987241168491-3.jpg"
    ],
    "units": 1,
    "featured": true,
    "cost": 32.14,
    "markup": 100,
    "badge": null,
    "badgeBg": "#9b59b6",
    "stock": 7,
    "rating": 4.5,
    "reviews": 0,
    "cardBg": "bg-[#d6eaf8]",
    "rotate": "rotate(-1deg)",
    "deco": "tape"
  },
];
